# Generated by Django 4.2.7 on 2023-11-23 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updatad_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('type_category', models.CharField(choices=[('AL', 'Alimento'), ('BE', 'Bebida')], max_length=2, verbose_name='Tipo de categoria')),
            ],
            options={
                'verbose_name': 'Categoria Restaurante',
                'verbose_name_plural': 'Categorias Restaurante',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updatad_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('logo', models.ImageField(upload_to='restaurants/', verbose_name='Logo')),
                ('contact', models.CharField(max_length=11, verbose_name='Telefone')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updatad_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Em estoque')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant/products/', verbose_name='Foto')),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Preço')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.categorymenu', verbose_name='Categoria')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.restaurant', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.AddField(
            model_name='categorymenu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.restaurant', verbose_name='Cardapio'),
        ),
    ]
