# Generated by Django 4.2.7 on 2023-12-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_alter_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='restaurant/products/', verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
